name: CI/CD - Deploy Seguro

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --audit-level=high

      - name: Run unit tests
        run: npm test

      - name: Build project
        run: npm run build

      # Despliegue opcional si tuvieras un servidor remoto
      # - name: Deploy to server
      #   env:
      #     HOST: ${{ secrets.SERVER_HOST }}
      #     USER: ${{ secrets.SERVER_USER }}
      #     KEY: ${{ secrets.SSH_KEY }}
      #   run: |
      #     scp -i $KEY -r ./build $USER@$HOST:/var/www/secureapp
      #     ssh -i $KEY $USER@$HOST "sudo systemctl restart nginx"
